# GitHub action to Build and deploy to Play Store
name: Build and deploy to Play Store

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-cache-

      - name: Set up keystore.properties
        run: |
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > android/key.properties

      - name: Download google-services.json
        run: echo "$FIREBASE_CONFIG" > ./android/app/google-services.json

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release app bundle
        run: flutter build appbundle --release
        env:
          KEYSTORE_PATH: android/key.jks
          KEYSTORE_ALIAS: my_keystore_alias
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Authenticate with Google Play Console
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-project-id
          service_account_key: ${{ secrets.PLAY_STORE_AUTH_TOKEN }}
      - name: Upload APK to Google Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          releaseFiles: "build/app/outputs/bundle/release/app-release.aab"
          track: "production"
          packageName: "com.ibhavikmakwana.flutterplayground"
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}